/**
 * Generated by ForkLaunch
 * File: test-utils.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { getEnvVar } from '@forklaunch/common';
import {
  BlueprintTestHarness,
  clearTestDatabase,
  DatabaseType,
  TEST_TOKENS,
  TestSetupResult
} from '@forklaunch/testing';
import { EntityManager, MikroORM } from '@mikro-orm/core';
import dotenv from 'dotenv';
import * as path from 'path';

export { TEST_TOKENS, TestSetupResult };

let harness: BlueprintTestHarness;

dotenv.config({ path: path.join(__dirname, '../.env.test') });

export const setupTestDatabase = async (): Promise<TestSetupResult> => {
  harness = new BlueprintTestHarness({
    getConfig: async () => {
      const { default: config } = await import('../mikro-orm.config');
      return config;
    },
    databaseType: getEnvVar('DATABASE_TYPE') as DatabaseType,
    useMigrations: true,
    migrationsPath: path.join(__dirname, getEnvVar("MIGRATIONS_PATH")),
    needsRedis: false,
    
  });

  return await harness.setup();
};

export const cleanupTestDatabase = async (): Promise<void> => {
  if (harness) {
    await harness.cleanup();
  }
};

export const clearDatabase = async (options?: {
  orm?: MikroORM;
  redis?: TestSetupResult['redis'];
}): Promise<void> => {
  await clearTestDatabase(options);
};


export const setupTestData = async (em: EntityManager) => {
  const { InnovationsRecord } = await import(
    '../persistence/entities/innovationsRecord.entity'
  );

  em.create(InnovationsRecord, {
    id: '123e4567-e89b-12d3-a456-426614174000',
    message: 'Test message'
  });

  await em.flush();
};


export const mockInnovationsData = {
  message: 'New test message'
};