/**
* Generated by ForkLaunch
* File: clientSdk.ts
* This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
*/
import type { IamSdkClient, BetterAuthConfig } from "@uchicago-ideas/iam";
import { RegistryOptions, universalSdk } from "@forklaunch/universal-sdk";
import { InnovationsSdkClient } from "@uchicago-ideas/innovations";
import { createAuthClient } from "better-auth/client";
import { inferAdditionalFields } from "better-auth/client/plugins";
//! export various service and worker sdk clients
export const iamSdkClient = async ({ host, registryOptions }: {
	host: string;
	registryOptions: RegistryOptions;
}) => ({
	core: await universalSdk<IamSdkClient>({
		host,
		registryOptions
	}),
	betterAuth: createAuthClient({
		baseURL: host,
		plugins: [inferAdditionalFields<BetterAuthConfig>()]
	})
});
export const innovationsSdkClient = universalSdk<InnovationsSdkClient>;
