/**
 * Generated by ForkLaunch
 * File: compliance.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { iamSdkClient, innovationsSdkClient } from './clientSdk';

type IamClient = Awaited<ReturnType<typeof iamSdkClient>>;
type InnovationsClient = Awaited<ReturnType<typeof innovationsSdkClient>>;

/**
 * Compliance fan-out client. Calls erase/export on every registered service
 * in parallel. Per-service responses are the exact discriminated unions
 * produced by each SDK (e.g. `{ code: 200; response: {...} } | { code: 404; response: string }`),
 * so callers narrow on `code` without any casts.
 *
 * This file is regenerated when services are added, removed, or renamed.
 *
 * Requires a JWT token from a user with SYSTEM role.
 */
export function createComplianceClient(config: {
  token: string;
  iam: IamClient;
  innovations: InnovationsClient;
}) {
  const headers = { authorization: `Bearer ${config.token}` } as const;

  return {
    async erase(userId: string) {
      const [iam, innovations] = await Promise.all([
        config.iam.core.compliance.eraseUserData({ params: { userId }, headers }),
        config.innovations.compliance.eraseUserData({ params: { userId }, headers })
      ]);
      return { iam, innovations };
    },

    async export(userId: string) {
      const [iam, innovations] = await Promise.all([
        config.iam.core.compliance.exportUserData({ params: { userId }, headers }),
        config.innovations.compliance.exportUserData({ params: { userId }, headers })
      ]);
      return { iam, innovations };
    }
  };
}
