/**
 * Generated by ForkLaunch
 * File: betterAuth.types.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { NextFunction, Request, Response } from '@uchicago-ideas/core';
import { Span } from '@opentelemetry/api';

export type BetterAuthRequest = Request & {
  path: string;
  originalPath?: string;

  context: {
    correlationId: string;
    span?: Span;
  };
};

export type BetterAuthResponse = Response;

export type BetterAuthNextFunction = NextFunction;