/**
 * Generated by ForkLaunch
 * File: innovations.interface.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { Schema } from '@forklaunch/validator';
import { SchemaValidator } from '@uchicago-ideas/core';
import {
  InnovationsRequestSchema,
  InnovationsResponseSchema
} from '../schemas/innovations.schema';

// When not using mappers, work directly with schema-validated types
type InnovationsRequest = Schema<typeof InnovationsRequestSchema, SchemaValidator>;
type InnovationsResponse = Schema<typeof InnovationsResponseSchema, SchemaValidator>;

// Interface that defines the methods that the InnovationsService must implement
export interface InnovationsService {
  innovationsPost: (
    data: InnovationsRequest
  ) => Promise<InnovationsResponse>;
}