/**
 * Generated by ForkLaunch
 * File: innovations.schema.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { string } from '@uchicago-ideas/core';

// idiomatic validator schema defines the request schema. This should extend the request type
export const InnovationsRequestSchema = { 
    message: string
};

// idiomatic validator schema defines the response schema. This should extend the response type
export const InnovationsResponseSchema = {
    message: string
};