/**
 * Generated by ForkLaunch
 * File: innovations.service.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { OpenTelemetryCollector } from '@forklaunch/core/http';
import { EntityManager } from '@mikro-orm/core';

import { Schema } from '@forklaunch/validator';
import { SchemaValidator } from '@uchicago-ideas/core';
import { Metrics } from '@uchicago-ideas/monitoring';
import { InnovationsService } from '../interfaces/innovations.interface';
import {
  InnovationsRequestSchema,
  InnovationsResponseSchema
} from '../schemas/innovations.schema';
import { InnovationsRecord } from '../../persistence/entities';

// When not using mappers, work directly with schema-validated types
type InnovationsRequest = Schema<typeof InnovationsRequestSchema, SchemaValidator>;
type InnovationsResponse = Schema<typeof InnovationsResponseSchema, SchemaValidator>;

// BaseInnovationsService class that implements the InnovationsService interface
export class BaseInnovationsService implements InnovationsService { 
  private entityManager: EntityManager;
  private readonly openTelemetryCollector: OpenTelemetryCollector<Metrics>;

  constructor(
    entityManager: EntityManager,
    openTelemetryCollector: OpenTelemetryCollector<Metrics>
  ) { 
    this.entityManager = entityManager;
    this.openTelemetryCollector = openTelemetryCollector;
  }

  // innovationsPost method that implements the InnovationsService interface
  innovationsPost = async (
    data: InnovationsRequest
  ): Promise<InnovationsResponse> => {
    // Map from request data to entity (inline DTO → Entity conversion)
    const entity = this.entityManager.create(InnovationsRecord, {
      ...data
    });
    await this.entityManager.persist(entity).flush();

    // Map from entity to response (inline Entity → DTO conversion)
    return entity;
  };
}