/**
 * Generated by ForkLaunch
 * File: innovationsRecord.seeder.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { EntityManager } from "@mikro-orm/core";
import { Seeder } from "@mikro-orm/seeder";
import { innovationsRecordData } from "../seed.data";
import { InnovationsRecord } from "../entities/innovationsRecord.entity";

export class InnovationsRecordSeeder extends Seeder {
  async run(em: EntityManager): Promise<void> {
    em.setFilterParams('tenant', { tenantId: 'seed' });
    const record = em.create(InnovationsRecord, innovationsRecordData);
    await em.persist(record).flush();
  }
}