/**
 * Generated by ForkLaunch
 * File: compliance.routes.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { forklaunchRouter, schemaValidator } from '@uchicago-ideas/core';
import { eraseUserData, exportUserData } from '../controllers/compliance.controller';
import { ci, tokens } from '../../bootstrapper';

const openTelemetryCollector = ci.resolve(tokens.OtelCollector);

export const complianceRouter = forklaunchRouter(
  '/compliance',
  schemaValidator,
  openTelemetryCollector
);

export const eraseUserDataRoute = complianceRouter.delete('/erase/:userId', eraseUserData);
export const exportUserDataRoute = complianceRouter.get('/export/:userId', exportUserData);