/**
 * Generated by ForkLaunch
 * File: innovations.routes.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { forklaunchRouter, schemaValidator } from '@uchicago-ideas/core';
import { innovationsGet, innovationsPost } from '../controllers/innovations.controller';
import { ci, tokens } from '../../bootstrapper';


// resolve the dependencies
const openTelemetryCollector = ci.resolve(tokens.OtelCollector);

// defines the router for the innovations routes
export const innovationsRouter = forklaunchRouter(
  '/innovations',
  schemaValidator, 
  openTelemetryCollector
);

// mount the routes
export const innovationsGetRoute = innovationsRouter.get('/', innovationsGet);
export const innovationsPostRoute = innovationsRouter.post('/', innovationsPost);