/**
 * Generated by ForkLaunch
 * File: registrations.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { createAuthCacheService, type AuthCacheService, number, SchemaValidator, string, type } from "@uchicago-ideas/core";
import { metrics } from "@uchicago-ideas/monitoring";
import { RedisTtlCache } from "@forklaunch/infrastructure-redis";
import { OpenTelemetryCollector } from "@forklaunch/core/http";
import {
  ComplianceDataService,
  createConfigInjector,
  getEnvVar,
  Lifetime,
  RetentionService,
} from "@forklaunch/core/services";
import { FieldEncryptor, wrapEmWithTenantContext } from "@forklaunch/core/persistence";
import { ForkOptions } from "@mikro-orm/core";
import { EntityManager, MikroORM } from "@mikro-orm/postgresql";
import mikroOrmOptionsConfig from './mikro-orm.config';
import { BaseInnovationsService } from "./domain/services/innovations.service";
import { EmailService } from "./domain/services/email.service";
import { IdeaEvaluationService } from "./domain/services/idea-evaluation.service";
import { getOrganization, type Organization } from "./domain/organizations";
import { PortalService } from "./domain/services/portal.service";

//! instantiates the config injector
const configInjector = createConfigInjector(SchemaValidator(), {
  SERVICE_METADATA: {
    lifetime: Lifetime.Singleton,
    type: {
      name: string,
      version: string,
    },
    value: {
      name: "uchicago-ideas-innovations",
      version: "0.1.0",
    },
  },
});
  
//! defines the environment configuration for the application
const environmentConfig = configInjector.chain({
  REDIS_URL: {
    lifetime: Lifetime.Singleton,
    type: string,
    value: getEnvVar('REDIS_URL')
  },
  PROTOCOL: {
    lifetime: Lifetime.Singleton,
    type: string,
    value: getEnvVar("PROTOCOL"),
  },
  HOST: {
    lifetime: Lifetime.Singleton,
    type: string,
    value: getEnvVar("HOST"),
  },
  PORT: {
    lifetime: Lifetime.Singleton,
    type: number,
    value: Number(getEnvVar("PORT")),
  },
  VERSION: {
    lifetime: Lifetime.Singleton,
    type: string,
    value: getEnvVar("VERSION") ?? "v1",
  },
  DOCS_PATH: {
    lifetime: Lifetime.Singleton,
    type: string,
    value: getEnvVar("DOCS_PATH") ?? "/docs",
  },
  OTEL_SERVICE_NAME: {
    lifetime: Lifetime.Singleton,
    type: string,
    value: getEnvVar("OTEL_SERVICE_NAME"),
  },
  OTEL_LEVEL: {
    lifetime: Lifetime.Singleton,
    type: string,
    value: getEnvVar("OTEL_LEVEL") || "info",
  },
  OTEL_EXPORTER_OTLP_ENDPOINT: {
    lifetime: Lifetime.Singleton,
    type: string,
    value: getEnvVar("OTEL_EXPORTER_OTLP_ENDPOINT"),
  },
  JWKS_PUBLIC_KEY_URL: {
    lifetime: Lifetime.Singleton,
    type: string,
    value: getEnvVar('JWKS_PUBLIC_KEY_URL')
  },
  IAM_URL: {
    lifetime: Lifetime.Singleton,
    type: string,
    value: getEnvVar('IAM_URL')
  },
  HMAC_SECRET_KEY: {
    lifetime: Lifetime.Singleton,
    type: string,
    value: getEnvVar('HMAC_SECRET_KEY')
  },
  ENCRYPTION_KEY: {
    lifetime: Lifetime.Singleton,
    type: string,
    value: getEnvVar('ENCRYPTION_KEY')
  },
  PORTAL_URL: {
    lifetime: Lifetime.Singleton,
    type: string,
    value: getEnvVar('PORTAL_URL') ?? 'http://localhost:5173'
  },
  RESEND_API_KEY: {
    lifetime: Lifetime.Singleton,
    type: string,
    value: getEnvVar('RESEND_API_KEY') ?? ''
  },
  EMAIL_FROM: {
    lifetime: Lifetime.Singleton,
    type: string,
    value:
      getEnvVar('EMAIL_FROM') ??
      'UChicago Medicine Ideas <onboarding@resend.dev>'
  },
  FOUNDRY_ENDPOINT: {
    lifetime: Lifetime.Singleton,
    type: string,
    value: getEnvVar('FOUNDRY_ENDPOINT') ?? ''
  },
  FOUNDRY_API_KEY: {
    lifetime: Lifetime.Singleton,
    type: string,
    value: getEnvVar('FOUNDRY_API_KEY') ?? ''
  },
  FOUNDRY_MODEL: {
    lifetime: Lifetime.Singleton,
    type: string,
    value: getEnvVar('FOUNDRY_MODEL') ?? ''
  },
  FOUNDRY_API_VERSION: {
    lifetime: Lifetime.Singleton,
    type: string,
    value: getEnvVar('FOUNDRY_API_VERSION') ?? '2024-05-01-preview'
  }
});

//! defines the runtime dependencies for the application
const runtimeDependencies = environmentConfig.chain({
  
  Orm: {
    lifetime: Lifetime.Singleton,
    type: MikroORM,
    factory: () => new MikroORM(mikroOrmOptionsConfig)
  },
  OtelCollector: {
    lifetime: Lifetime.Singleton,
    type: OpenTelemetryCollector,
    factory: ({ OTEL_SERVICE_NAME, OTEL_LEVEL }) =>
      new OpenTelemetryCollector(
        OTEL_SERVICE_NAME,
        OTEL_LEVEL || "info",
        metrics
      ),
  },
  TtlCache: {
    lifetime: Lifetime.Singleton,
    type: RedisTtlCache,
    factory: ({ REDIS_URL, OtelCollector, ENCRYPTION_KEY }) =>
      new RedisTtlCache(60 * 60 * 1000, OtelCollector, {
        url: REDIS_URL,
      }, {
        enabled: true,
        level: "info",
      }, {
        encryptor: new FieldEncryptor(ENCRYPTION_KEY),
      }),
  },
  EntityMgr: {
    lifetime: Lifetime.Scoped,
    type: EntityManager,
    factory: (
      { Orm },
      context?: { entityManagerOptions?: ForkOptions; tenantId?: string }
    ) =>
      wrapEmWithTenantContext(
        Orm.em.fork(context?.entityManagerOptions),
        context?.tenantId
      ) as EntityManager,
  },
  AuthCacheService: {
    lifetime: Lifetime.Singleton,
    type: type<AuthCacheService>(),
    factory: ({ TtlCache }) => createAuthCacheService(TtlCache)
  },
});

//! defines the service dependencies for the application
const serviceDependencies = runtimeDependencies.chain({
  EmailService: {
    lifetime: Lifetime.Singleton,
    type: EmailService,
    factory: ({ OtelCollector, PORTAL_URL, RESEND_API_KEY, EMAIL_FROM }) =>
      new EmailService(OtelCollector, PORTAL_URL, RESEND_API_KEY, EMAIL_FROM)
  },
  IdeaEvaluationService: {
    lifetime: Lifetime.Singleton,
    type: IdeaEvaluationService,
    factory: ({
      OtelCollector,
      FOUNDRY_ENDPOINT,
      FOUNDRY_API_KEY,
      FOUNDRY_MODEL,
      FOUNDRY_API_VERSION
    }) =>
      new IdeaEvaluationService(
        OtelCollector,
        FOUNDRY_ENDPOINT,
        FOUNDRY_API_KEY,
        FOUNDRY_MODEL,
        FOUNDRY_API_VERSION
      )
  },
  PortalService: {
    lifetime: Lifetime.Scoped,
    type: PortalService,
    factory: (
      { EntityMgr, EmailService, IdeaEvaluationService, OtelCollector },
      context?: { organization?: Organization }
    ) =>
      new PortalService(
        EntityMgr,
        EmailService,
        IdeaEvaluationService,
        OtelCollector,
        context?.organization ?? getOrganization()
      )
  },
  InnovationsService: {
    lifetime: Lifetime.Scoped,
    type: BaseInnovationsService,
    factory: ({ 
      EntityMgr,
      OtelCollector
    }) =>
      new BaseInnovationsService(
        EntityMgr,
        OtelCollector
      )
  },
  RetentionService: {
    lifetime: Lifetime.Singleton,
    type: RetentionService,
    factory: ({ Orm, OtelCollector }) =>
      new RetentionService(Orm, OtelCollector)
  },
  ComplianceDataService: {
    lifetime: Lifetime.Singleton,
    type: ComplianceDataService,
    factory: ({ Orm, OtelCollector }) =>
      new ComplianceDataService(Orm, OtelCollector)
  }
});

//! validates the configuration and returns the dependencies for the application
export const createDependencyContainer = (envFilePath: string) => ({
  ci: serviceDependencies.validateConfigSingletons(envFilePath),
  tokens: serviceDependencies.tokens()
});