/**
 * Generated by ForkLaunch
 * File: sdk.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { SchemaValidator } from "@uchicago-ideas/core";
import { MapToSdk } from '@forklaunch/core/http';
import {
  innovationsGet,
  innovationsPost,
  eraseUserData,
  exportUserData,
  requestAccess,
  getNda,
  getMe,
  acceptNda,
  submitIdea,
  evaluateIdea,
  refineIdea,
  storageInspector,
  adminListIdeas
} from "./api/controllers";

//! defines the sdk type for deep linking with types
export type InnovationsSdk = {
  innovations: {
    innovationsGet: typeof innovationsGet;
    innovationsPost: typeof innovationsPost;
  };
  portal: {
    requestAccess: typeof requestAccess;
    getNda: typeof getNda;
    getMe: typeof getMe;
    acceptNda: typeof acceptNda;
    submitIdea: typeof submitIdea;
    evaluateIdea: typeof evaluateIdea;
    refineIdea: typeof refineIdea;
    storageInspector: typeof storageInspector;
  };
  admin: {
    adminListIdeas: typeof adminListIdeas;
  };
  compliance: {
    eraseUserData: typeof eraseUserData;
    exportUserData: typeof exportUserData;
  };
};

//! creates an instance of the sdkClient
export const innovationsSdkClient = {
  innovations: {
    innovationsGet: innovationsGet,
    innovationsPost: innovationsPost
  },
  portal: {
    requestAccess,
    getNda,
    getMe,
    acceptNda,
    submitIdea,
    evaluateIdea,
    refineIdea,
    storageInspector
  },
  admin: {
    adminListIdeas
  },
  compliance: {
    eraseUserData,
    exportUserData
  }
} satisfies InnovationsSdk;

//! exports the universally friendly sdk typings
export type InnovationsSdkClient = MapToSdk<SchemaValidator, InnovationsSdk>;