/**
 * Generated by ForkLaunch
 * File: server.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { forklaunchExpress, PERMISSIONS, ROLES, SchemaValidator } from '@uchicago-ideas/core';
import { createSurfacePermissions, createSurfaceRoles } from '@uchicago-ideas/iam';
import { innovationsRouter } from './api/routes/innovations.routes';
import { adminRouter, portalRouter } from './api/routes/portal.routes';
import { complianceRouter } from './api/routes/compliance.routes';
import { setupRls, setupTenantFilter } from '@forklaunch/core/persistence';
import { ci, tokens } from './bootstrapper';
import { innovationsSdkClient } from './sdk';

/**
 * Creates an instance of OpenTelemetryCollector
 */
const openTelemetryCollector = ci.resolve(tokens.OtelCollector);
const orm = ci.resolve(tokens.Orm);
setupTenantFilter(orm, { logger: openTelemetryCollector });
setupRls(orm, { logger: openTelemetryCollector });


const authCacheService = ci.resolve(tokens.AuthCacheService);
const iamUrl = ci.resolve(tokens.IAM_URL);
const hmacSecretKey = ci.resolve(tokens.HMAC_SECRET_KEY);


/**
 * Creates surfacing functions for authentication
 */
async function createAuthOptions() {

  // Only IAM is configured
  const [surfaceRoles, surfacePermissions] = await Promise.all([
    createSurfaceRoles({ authCacheService, iamUrl, hmacSecretKey }),
    createSurfacePermissions({ authCacheService, iamUrl, hmacSecretKey })
  ]);

  return {
    surfaceRoles,
    surfacePermissions,
    surfaceFeatures: async () => { throw new Error('Billing not configured: surfaceFeatures is not implemented'); },
    surfaceSubscription: async () => { throw new Error('Billing not configured: surfaceSubscription is not implemented'); }
  };

}

/**
 * Starts the server with configured auth options
 */
async function startServer() {
  const authOptions = await createAuthOptions();

  /**
   * Creates an instance of forklaunchExpress
   */
  const app = forklaunchExpress(SchemaValidator(), openTelemetryCollector, {
    auth: authOptions
  });

  //! resolves the protocol, host, port, and version from the configuration
  const protocol = ci.resolve(tokens.PROTOCOL);
  const host = ci.resolve(tokens.HOST);
  const port = ci.resolve(tokens.PORT);
  const version = ci.resolve(tokens.VERSION);
  const docsPath = ci.resolve(tokens.DOCS_PATH);

  //! mounts the routes to the app
  app.use(innovationsRouter);
  app.use(portalRouter);
  app.use(adminRouter);
  app.use(complianceRouter);

  //! mounts the sdk to the app
  app.registerSdks(innovationsSdkClient);

  //! starts the server
  app.listen(port, host, () => {
    openTelemetryCollector.info(
      `🎉 Innovations Server is running at ${protocol}://${host}:${port} 🎉.
      // An API reference can be accessed at ${protocol}://${host}:${port}/api/${version}${docsPath}`
    );
  });
}

startServer().catch((error) => {
  console.error('Failed to start server:', error);
  process.exit(1);
});