/**
 * Generated by ForkLaunch
 * File: member.entity.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { defineComplianceEntity, fp } from '@forklaunch/core/persistence';
import type { InferEntity } from '@mikro-orm/core';
import { sqlBaseProperties } from '@uchicago-ideas/core';

export const Member = defineComplianceEntity({
  name: 'Member',
  properties: {
    ...sqlBaseProperties,
    organizationId: fp.string().compliance('none'),
    userId: fp.string().compliance('none'),
    role: fp.string().default('member').compliance('none')
  }
});

export type Member = InferEntity<typeof Member>;