/**
 * Generated by ForkLaunch
 * File: organizationRole.entity.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { defineComplianceEntity, fp } from '@forklaunch/core/persistence';
import type { InferEntity } from '@mikro-orm/core';
import { sqlBaseProperties } from '@uchicago-ideas/core';

export const OrganizationRole = defineComplianceEntity({
  name: 'OrganizationRole',
  properties: {
    ...sqlBaseProperties,
    organizationId: fp.string().compliance('none'),
    role: fp.string().compliance('none'),
    permission: fp.string().compliance('none')
  }
});

export type OrganizationRole = InferEntity<typeof OrganizationRole>;