/**
 * Generated by ForkLaunch
 * File: seed.data.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { RequiredEntityData } from '@mikro-orm/core';
import { v4 as uuidv4 } from 'uuid';
import { User } from '../persistence/entities/user.entity';
import { Account } from './entities/account.entity';
import { Session } from './entities/session.entity';
import { Verification } from './entities/verification.entity';

//! Begin seed data

export const user = {
  id: uuidv4(),
  email: 'test@test.com',
  emailVerified: true,
  name: 'test',
  firstName: 'Test',
  lastName: 'User',
  providerFields: null
} satisfies RequiredEntityData<User>;

export const account = {
  user: user.id,
  providerId: 'test',
  accountId: 'test',
  accessToken: 'test',
  refreshToken: 'test',
  accessTokenExpiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24),
  refreshTokenExpiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24)
} satisfies RequiredEntityData<Account>;

export const session = {
  user: user.id,
  token: 'test',
  expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24),
  ipAddress: '127.0.0.1',
  userAgent: 'test'
} satisfies RequiredEntityData<Session>;

export const verification = {
  identifier: 'test',
  value: 'test',
  expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24)
} satisfies RequiredEntityData<Verification>;