/**
 * Generated by ForkLaunch
 * File: discovery.routes.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { forklaunchRouter, schemaValidator } from '@uchicago-ideas/core';
import { ci, tokens } from '../../bootstrapper';
import { getAuthMethods } from '../controllers/discovery.controller';

const openTelemetryCollector = ci.resolve(tokens.OtelCollector);

export const discoveryRouter = forklaunchRouter(
  '/discovery',
  schemaValidator,
  openTelemetryCollector
);

export const getAuthMethodsRoute = discoveryRouter.get(
  '/auth-methods',
  getAuthMethods
);