/**
 * Generated by ForkLaunch
 * File: user.routes.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { forklaunchRouter, schemaValidator } from '@uchicago-ideas/core';
import { ci, tokens } from '../../bootstrapper';
import {
  surfacePermissions,
  surfaceRoles
} from '../controllers/user.controller';

const openTelemetryCollector = ci.resolve(tokens.OtelCollector);

export const userRouter = forklaunchRouter(
  '/user',
  schemaValidator,
  openTelemetryCollector
);

export const surfaceRolesRoute = userRouter.get(
  '/:id/surface-roles',
  surfaceRoles
);
export const surfacePermissionsRoute = userRouter.get(
  '/:id/surface-permissions',
  surfacePermissions
);