/**
 * Generated by ForkLaunch
 * File: index.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

export * from './access-key.entity';
export * from './doctor.entity';
export * from './idea.entity';
export * from './innovationsRecord.entity';
export * from './nda-acceptance.entity';
