/**
 * Generated by ForkLaunch
 * File: innovationsRecord.entity.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { defineComplianceEntity, fp } from '@forklaunch/core/persistence';
import type { InferEntity } from '@mikro-orm/core';
import { sqlBaseProperties } from '@uchicago-ideas/core';

export const InnovationsRecord = defineComplianceEntity({
  name: 'InnovationsRecord',
  properties: {
    ...sqlBaseProperties,
    message: fp.string().compliance('none'),
  },
});

export type InnovationsRecord = InferEntity<typeof InnovationsRecord>;