/**
 * Generated by ForkLaunch
 * File: mikro-orm.config.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { createConfigInjector, getEnvVar, Lifetime } from '@forklaunch/core/services';
import { FieldEncryptor, registerEncryptor } from '@forklaunch/core/persistence';

import { Migrator } from '@mikro-orm/migrations';
import { number, SchemaValidator, string } from '@uchicago-ideas/core';
import { Platform, TextType, Type } from '@mikro-orm/core';
import { defineConfig } from '@mikro-orm/postgresql';
import dotenv from 'dotenv';
import * as entities from './persistence/entities';

//! Load the environment variables
dotenv.config({ path: getEnvVar('DOTENV_FILE_PATH') });

//! Create the config injector
const configInjector = createConfigInjector(
  SchemaValidator(),
  {
    DB_NAME: {
      lifetime: Lifetime.Singleton,
      type: string,
      value: getEnvVar('DB_NAME')
    },
    DB_HOST: {
      lifetime: Lifetime.Singleton,
      type: string,
      value: getEnvVar('DB_HOST')
    },
    DB_USER: {
      lifetime: Lifetime.Singleton,
      type: string,
      value: getEnvVar('DB_USER')
    },
    DB_PASSWORD: {
      lifetime: Lifetime.Singleton,
      type: string,
      value: getEnvVar('DB_PASSWORD')
    },
    DB_PORT: {
      lifetime: Lifetime.Singleton,
      type: number,
      value: Number(getEnvVar('DB_PORT'))
    }, 
    NODE_ENV: {
      lifetime: Lifetime.Singleton,
      type: string,
      value: getEnvVar('NODE_ENV')
    },
    ENCRYPTION_KEY: {
      lifetime: Lifetime.Singleton,
      type: string,
      value: getEnvVar('ENCRYPTION_KEY')
    }
  }
);

//! Validate the config injector
export const validConfigInjector = configInjector.validateConfigSingletons(
  getEnvVar('DOTENV_FILE_PATH')
);
const tokens = validConfigInjector.tokens();

//! Register the field encryptor
registerEncryptor(new FieldEncryptor(validConfigInjector.resolve(tokens.ENCRYPTION_KEY)));

//! Define the mikro-orm options config
const mikroOrmOptionsConfig = defineConfig({ 
  dbName: validConfigInjector.resolve(
    tokens.DB_NAME
  ),
  host: validConfigInjector.resolve(
    tokens.DB_HOST
  ),
  user: validConfigInjector.resolve(
    tokens.DB_USER
  ),
  password: validConfigInjector.resolve(
    tokens.DB_PASSWORD
  ),
  port: validConfigInjector.resolve(
    tokens.DB_PORT
  ),
  driverOptions: {
    ssl: validConfigInjector.resolve(tokens.NODE_ENV) !== 'development'
  },
  entities: Object.values(entities),
  debug: validConfigInjector.resolve(
    tokens.NODE_ENV
  ) === 'development',
  extensions: [Migrator],
  discovery: {
    getMappedType(type: string, platform: Platform) {
      // override the mapping for string properties only
      if (type === 'string') {
        return Type.getType(TextType);
      }

      return platform.getDefaultMappedType(type);
    }
  },
  migrations: {
    path: 'migrations-postgresql'
  },
  // Individual seeders live in persistence/seeders/ and are wired through DatabaseSeeder.
  seeder: {
    path: 'persistence',
    glob: 'seeder.ts'
  },
  allowGlobalContext: true
});

//! Export the mikro-orm options config
export default mikroOrmOptionsConfig;