/**
 * Generated by ForkLaunch
 * File: seed.data.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { InnovationsRecord } from './entities/innovationsRecord.entity';
import { InferEntity, RequiredEntityData } from '@mikro-orm/core';
//! Begin seed data
export const innovationsRecordData = {
  message: 'Hello, world!'
} satisfies RequiredEntityData<InferEntity<typeof InnovationsRecord>>;