/**
 * Generated by ForkLaunch
 * File: index.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

export * from "./innovations.controller";
export * from "./compliance.controller";
export * from "./portal.controller";