/**
 * Generated by ForkLaunch
 * File: innovations.controller.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { handlers, ROLES, schemaValidator } from '@uchicago-ideas/core';


import { InnovationsRequestSchema, InnovationsResponseSchema } from '../../domain/schemas/innovations.schema';

import { ci, tokens } from '../../bootstrapper';

//! resolve the dependencies
//! scopeFactory creates a new dependency injection scope for the service
const scopeFactory = () => ci.createScope();
// serviceFactory returns a new service instance on demand
const serviceFactory = ci.scopedResolver(tokens.InnovationsService);
// openTelemetryCollector for collecting logs and metrics with appropriate context
const openTelemetryCollector = ci.resolve(tokens.OtelCollector);
//! resolve the JWKS public key URL
const JWKS_PUBLIC_KEY_URL = ci.resolve(tokens.JWKS_PUBLIC_KEY_URL);

  // GET endpoint handler that returns a simple message
export const innovationsGet = handlers.get(
  schemaValidator,
  '/',
  {
    name: 'Innovations Get',
    summary: 'Gets Innovations',
    access: 'protected',
    auth: {
      jwt: {
        jwksPublicKeyUrl: JWKS_PUBLIC_KEY_URL
      },
      allowedRoles: new Set([ROLES.ADMIN])
    },
    responses: {
      
      
      200: InnovationsResponseSchema
      
    }
  },
  async (req, res) => {
    res.status(200).json({
      message: 'Innovations'
    });
  }
);

// POST endpoint handler that processes request body and returns response from service
export const innovationsPost = handlers.post(
  schemaValidator,
  '/',
  {
    name: 'Innovations Post',
    summary: 'Posts Innovations',
    access: 'protected',
    auth: {
      jwt: {
        jwksPublicKeyUrl: JWKS_PUBLIC_KEY_URL
      },
      allowedRoles: new Set([ROLES.ADMIN])
    },
    
    
    body: InnovationsRequestSchema,
    
    responses: {
      
      
      200: InnovationsResponseSchema
      
    }
  },
  async (req, res) => {
    res
      .status(200)
      .json(
        // constructs a new service instance using the scopeFactory and calls the innovationsPost method
        await serviceFactory(
          { scope: scopeFactory() }
        ).innovationsPost(req.body)
      );
  }
);