/**
 * Generated by ForkLaunch
 * File: innovations.types.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { Schema } from '@forklaunch/validator';
import { SchemaValidator } from '@uchicago-ideas/core';
import { InnovationsRequestSchema, InnovationsResponseSchema } from '../schemas/innovations.schema';

// Exported type that matches the request schema
export type InnovationsRequestDto = Schema<typeof InnovationsRequestSchema, SchemaValidator>;

// Exported type that matches the response schema
export type InnovationsResponseDto = Schema<typeof InnovationsResponseSchema, SchemaValidator>;